# s3www configuration
s3www:
  image:
    repository: y4m4/s3www
    tag: latest
    pullPolicy: IfNotPresent
  
  replicas: 1
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# MinIO configuration  
minio:
  image:
    repository: quay.io/minio/minio
    tag: latest
  
  storage: 10Gi
  accessKey: minioadmin
  secretKey: minioadmin
  
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# Service configuration
service:
  type: NodePort
  nodePort:

# Ingress configuration
ingress:
  enabled: true
  hostname: s3www.local
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

# Monitoring configuration
monitoring:
  enabled: true
  
  metricsServer:
    enabled: true
    version: "v0.8.0"
    imageTag: "v0.8.0"
    kubeletInsecureTls: true
    extraArgs: []
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 200Mi
    
  resources:
    enabled: true
    
podLabels:
  app.kubernetes.io/name: s3www
  app.kubernetes.io/component: web-server
  monitoring.coreos.com/enabled: "true"
