apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  access-key: {{ .Values.minio.accessKey | b64enc | quote }}
  secret-key: {{ .Values.minio.secretKey | b64enc | quote }}