apiVersion: v1
kind: Service
metadata:
  name: s3www-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: s3www
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: s3www