apiVersion: v1
kind: Service
metadata:
  name: s3www-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: s3www
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 8080
    {{- if eq .Values.service.type "NodePort" }}
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    {{- end }}
    protocol: TCP
    name: http
  selector:
    app: s3www
